#!/usr/bin/env bash

case "$(printf "Kill\nSuspend\nHibernate\nReboot\nShutdown" | dmenu -i -c -bw 1 -l 5)" in
	Kill) ps -u "$USER" -o pid,comm,%cpu,%mem | dmenu -i -c -bw 1 -l 10 -p Kill: | awk '{print $1}' | xargs -r kill ;;
	Suspend) slock systemctl suspend -i ;;
    Hibernate) slock systemctl hibernate -i ;;
	Reboot) systemctl reboot -i ;;
	Shutdown) shutdown now ;;
	*) exit 1 ;;
esac
