#!/bin/sh

status=$(cat /sys/class/power_supply/ADP?*/online)
battery=$(cat /sys/class/power_supply/BAT?*/capacity)

if [ "$status" -eq 1 ]; then
    icon="󰂄"
else
    if [ "$battery" -le 20 ]; then
        icon=" "
    elif [ "$battery" -lt 60 ]; then
        icon=" "
    elif [ "$battery" -eq 100 ]; then
        icon=" "
    else
        icon=" "
    fi
fi

echo "$icon $battery%"
